# locators/login_locators.py
class LoginLocators:
    USERNAME = "input[name='username']"
    PASSWORD = "input[name='password']"
    LOGIN_BUTTON = "button[type='submit']"
    DASHBOARD_HEADER = "h6.oxd-topbar-header-breadcrumb-module"
    ERROR_MESSAGE = "p.oxd-text--toast-message"  # adjust if needed
    BRANDING_IMAGE = "img[alt='company-branding']"
    FORGOT_PASSWORD_LINK = "p.oxd-text--p.orangehrm-login-forgot-header"
    RESET_PASSWORD_HEADER = "h6.oxd-text--h6.orangehrm-forgot-password-title"
    RESET_PASSWORD_INSTRUCTION = "p.oxd-text--p.orangehrm-forgot-password-description"
    RESET_PASSWORD_INPUT = "input[placeholder='Username']"
    RESET_PASSWORD_BUTTON = "button[type='submit']"
    CANCEL_BUTTON = "button[type='button']"
    FOOTER_TEXT = "p.oxd-text--p.orangehrm-copyright"
    LANGUAGE_DROPDOWN = "div.oxd-select-text--after"
    LANGUAGE_OPTIONS = "div.oxd-select-dropdown > div"
    REMEMBER_ME_CHECKBOX = "input[type='checkbox']"
    REMEMBER_ME_LABEL = "span.oxd-checkbox-text"
    SHOW_PASSWORD_ICON = "i.oxd-icon.bi-eye"
    HIDE_PASSWORD_ICON = "i.oxd-icon.bi-eye-slash"
    LOGIN_PANEL_HEADER = "h5.oxd-text--h5.orangehrm-login-title"
    LOGIN_PANEL_SUBHEADER = "p.oxd-text--p.orangehrm-login-subtitle"
    LOGIN_PANEL = "div.orangehrm-login-form"
    LOGIN_PANEL_FOOTER = "div.orangehrm-login-footer"
    LOGIN_PANEL_FOOTER_LINKS = "div.orangehrm-login-footer a"
    LOGIN_PANEL_FOOTER_TEXT = "div.orangehrm-login-footer p"
    DASHBOARD_WELCOME_MESSAGE = "p.oxd-text--p.oxd-userdropdown-name"
    DASHBOARD_USER_DROPDOWN = "p.oxd-text--p.oxd-userdropdown-name"
    DASHBOARD_LOGOUT_OPTION = "a.oxd-userdropdown-link"
    DASHBOARD_PROFILE_OPTION = "a.oxd-userdropdown-link[href*='profile']"
